name: serpapi-dotnet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['8.0.x']
        #dotnet: ['6.0.x', '7.0.x', '8.0.x']
    name: test with Dotnet ${{ matrix.dotnet }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: test
        run: make all
        env:
          API_KEY: ${{secrets.API_KEY}}
          DOTNET_VERSION: ${{matrix.dotnet}}
